### ISSUE TITLE
I have the same Problem like you.

### ISSUE THREAD

**Issue by ValonK** [duggulous/MediaElementIssueExample#1]
Hello,

i know the problem is old but finally found the same problem that I have the exact same setup like you with  h264 videos and sometimes the mediaelement just fails. Can you tell me how you've fixed this? 

Thanks

**Comment by duggulous** [comment]
Oh jeez.  It has been a long time since I logged in to github.  Sorry, I didn't see this sooner.  
I ended up fixing my issue by re-encoding my videos as wmv.  I never could get the mp4 to work.
